version: '3.9'
services:
  backend:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ambassadorDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379
